import { GetProductRequestResponseDTO } from "@/dtos/productRequest";

export const products: GetProductRequestResponseDTO[] = [
  {
    id: 1,
    name: "Laptop",
    desc: "A high-performance laptop for work and play.",
    images: ["https://example.com/laptop1.jpg", "https://example.com/laptop2.jpg"],
    budget: 1500,
    quantity: 1,
    category: "Electronics",
    user_id: "user123",
    delivery_status: "Opening",
    from: "New York",
    to: "London",
    check_service: true,
    create_at: new Date("2023-10-26T10:00:00Z"),
    updated_at: new Date("2023-10-26T10:00:00Z"),
    deleted_at: new Date("2023-10-26T10:00:00Z"),
  },
  {
    id: 2,
    name: "Designer Handbag",
    desc: "A stylish and elegant handbag from a top designer.",
    images: ["https://example.com/bag1.jpg"],
    budget: 800,
    quantity: 1,
    category: "Fashion",
    user_id: "user456",
    delivery_status: "Pending",
    from: "Paris",
    to: "Tokyo",
    check_service: false,
    create_at: new Date("2023-10-27T14:30:00Z"),
    updated_at: new Date("2023-10-27T14:30:00Z"),
    deleted_at: new Date("2023-10-26T10:00:00Z"),
  },
  {
    id: 3,
    name: "Smartphone",
    desc: "Latest model smartphone with advanced features.",
    images: ["https://example.com/phone1.jpg", "https://example.com/phone2.jpg", "https://example.com/phone3.jpg"],
    budget: 1200,
    quantity: 2,
    category: "Electronics",
    user_id: "user789",
    delivery_status: "Opening",
    from: "Sydney",
    to: "Berlin",
    check_service: true,
    create_at: new Date("2023-10-28T09:15:00Z"),
    updated_at: new Date("2023-10-28T09:15:00Z"),
    deleted_at: new Date("2023-10-26T10:00:00Z"),
  },
  {
    id: 4,
    name: "Running Shoes",
    desc: "Comfortable and durable running shoes for athletes.",
    images: ["https://example.com/shoes1.jpg"],
    budget: 150,
    quantity: 1,
    category: "Sports",
    user_id: "user101",
    delivery_status: "Pending",
    from: "Los Angeles",
    to: "Rome",
    check_service: false,
    create_at: new Date("2023-10-29T16:45:00Z"),
    updated_at: new Date("2023-10-29T16:45:00Z"),
    deleted_at: new Date("2023-10-26T10:00:00Z"),
  },
  {
      id: 5,
      name: "Smart Watch",
      desc: "Latest smart watch with health and fitness tracking.",
      images: ["https://example.com/watch1.jpg", "https://example.com/watch2.jpg"],
      budget: 300,
      quantity: 1,
      category: "Electronics",
      user_id: "user202",
      delivery_status: "Opening",
      from: "Toronto",
      to: "Madrid",
      check_service: true,
      create_at: new Date("2023-10-30T11:30:00Z"),
      updated_at: new Date("2023-10-30T11:30:00Z"),
      deleted_at: new Date("2023-10-26T10:00:00Z"),
  },
];